### ISSUE TITLE
Minor editorial issues (mainly with formatting)

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#109]
Please see the attached document for screenshots of the issues.

- [ ] Table 21. Hyperlink needs fixing so that it is rendered a a hyperlink.
- [ ] Requirement 2. Create a blank line above the first bullet item so that asciidoc recognises it as a list.
- [ ] Requirement 28. Create a blank line above the first bullet item so that asciidoc recognises it as a list.
- [ ] Requirement 30. Create a blank line above the first bullet item so that asciidoc recognises it as a list.
- [ ] Abstract Test 13. The [ats_core_job-creation-mode] anchor is missing.
- [ ] Table 20. Hyperlink needs fixing so that it is rendered a a hyperlink.

[ogcapi-processes-editorial.pdf](https://github.com/opengeospatial/wps-rest-binding/files/5602859/ogcapi-processes-editorial.pdf)

**Comment by bpross-52n** [comment]
Fixed by PR https://github.com/opengeospatial/ogcapi-processes/pull/132
