### ISSUE TITLE
Change processCollection.yaml to processList.yaml in Table 12 

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#110]
Change `processCollection.yaml` to `processList.yaml` in Table 12 

![Screenshot 2020-11-26 at 12 30 49](https://user-images.githubusercontent.com/18121038/100351355-3c426d00-2fe3-11eb-8ad2-2f8c44fed7af.png)

**Comment by bpross-52n** [comment]
Done.
