### ISSUE TITLE
Issues identified in OGC-NA review

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#114]
- [x] **Issue 1**

 
The URIs of the Abstract Tests in Section A.7 use the 'collection' term, whereas the Conformance class uses the 'list' term.
 
Actions required:
* Change `/conf/job-collection/job-collection-op` to `/conf/job-list/job-list-op`
* Change `/conf/job-collection/job-collection-success` to `/conf/job-list/job-list-success`
 
 
- [x] **Issue 2**
 
Note as well that the requirement URIs in Section A.7 also use the ‘collection’ term. They should be using the ‘list’ term to be consistent with the requirement URIs in Section 12.
 
Actions required:
* Change `/req/job-collection/job-collection-op` to `/req/job-list/job-list-op`
* Change `/req/job-collection/job-collection-success` to `/req/job-list/job-list-success`
 
- [x] **Issue 3**
 
Requirement 30 has a double slash /req//html/content
 
 
- [ ] **Issue 4**
 
Abstract Test 8 uses the ‘collection’ term.
 
* /conf/core/process-collection
* /req/core/process-collection
* /req/core/process-collection-success
 
Actions required:
* Change to the correct URI that uses the ‘list’ term.
 
 
- [x] **Issue 5**
 
Abstract Test 9 uses the ‘collection’ term.
 
* /conf/core/process-collection-success
* /req/core/process-collection-success
 
Actions required:
* Change to the correct URI that uses the ‘list’ term.

**Comment by bpross-52n** [comment]
Renaming collection to list was done in version 1.0-draft.5: https://htmlpreview.github.io/?https://github.com/opengeospatial/ogcapi-processes/blob/master/docs/18-062.html
