### ISSUE TITLE
maximumMegabytes type to number

### ISSUE THREAD

**Issue by dcore94** [opengeospatial/ogcapi-processes#118]
We would like to be able to inject scripted rules that configure a process. In order to increase safety we'd like to restrict size of complex data to 1Kb or less but this is not possible as maximumMegabytes is typed to integer [[1](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/formatDescription.yaml#L5)].

Could it be changed to Number?

**Comment by bpross-52n** [comment]
We will discuss this at our next meeting on January 25th.
