### ISSUE TITLE
Change "processes" link relation type to be compliant with the OGC NA policy

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#128]
Right now `"processes"` is used
It should be a full URL like:
`"http://www.opengis.net/def/rel/ogc/1.0/processes"`

**Comment by bpross-52n** [comment]
Thanks, do you have a reference?

**Comment by jerstlouis** [comment]
@ghobona what would be the reference for this policy?

**Comment by bpross-52n** [comment]
I want to check which other relations this might concern. Or is it just processes?

**Comment by jerstlouis** [comment]
@bpross-52n that should apply to all relation types that are not already defined by IANA at https://www.iana.org/assignments/link-relations

I guess this also applies to `process-desc` and `execute`?

**Comment by jerstlouis** [comment]
See #149 for changing `process-desc` to `self`, following OGC convention for summarized list element pointing to full object.

**Comment by jerstlouis** [comment]
@pvretano @bpross-52n This issue needs to be addressed for 1.0. Related to #149

**Comment by fmigneault** [comment]
Wouldn't `describes` or `describedBy` names be appropriate to replace `process-desc`? 
as per https://www.iana.org/assignments/link-relations/link-relations.xhtml

I don't see much problem with `process-desc` in itself. It somewhat imitates `service-desc` that is valid.

**Comment by jerstlouis** [comment]
@fmigneault `describedby` is spelled all lowercase (https://www.iana.org/assignments/link-relations/link-relations.xhtml).

But in this case, as we discussed again during the workshop this should really be self, because it is a link to a more detailed version of the object itself in the context where the link is specified (in the process object element inside the list of processes).

This is used in multiple places in OGC APIs and we need to be consistent in the pattern.

See http://joanma.uab.cat/temp/graphs/OGCAPItiles.htm

It is used in:
- List of collections
- List of tilesets
- List of tile matrix sets
- List of processes

**Comment by fmigneault** [comment]
Yes. I'm good with including both. 
Are the links `http://www.opengis.net/def/rel/ogc/1.0/<ref>` planed to become actual definitions once the 1.0 version is released?

**Comment by jerstlouis** [comment]
@fmigneault They should get registered with the OGC NA, as e.g. `items` already is:
http://www.opengis.net/def/rel/ogc/1.0/items

**Comment by ghobona** [comment]
@jerstlouis The policy is at https://docs.ogc.org/pol/20-059r4.html

The register is at http://www.opengis.net/def/rel

**Comment by ghobona** [comment]
Clause 6.9

**Comment by jerstlouis** [comment]
Thanks @ghobona !

https://docs.ogc.org/pol/20-059r4.html#_link_relation_types

**Comment by bpross-52n** [comment]
Peter will create a PR for this.

**Comment by pvretano** [comment]
Resolved by PR #220.
