### ISSUE TITLE
Are these properties missing: complexInputId, complexInputsId, boundingboxInputId and literalInputId ?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#139]
The `execute` request example in [Section 7.9.2](http://docs.ogc.org/DRAFTS/18-062.html#_request_body) includes the following JSON properties: complexInputId, complexInputsId, boundingboxInputId and literalInputId. The example is reproduced below.

However, the OpenAPI definition does not include those properties.

If the example has a typo, then there are implications for Issue https://github.com/opengeospatial/ogcapi-processes/issues/123 as well.

```json
{
	"id": "EchoProcess",
	"inputs": {
		"complexInputId": {
			"format": {
				"mediaType": "application/xml"
			},
			"value": "<test/>"
		},
		"complexInputsId": [
			{
				"format": {
					"mediaType": "text/plain",
					"encoding": "UTF-8"
				},
				"value": "test"
			},
			{
				"format": {
					"mediaType": "text/plain",
					"encoding": "UTF-8"
				},
				"href": "https://test.data/test.txt"
			}
		],
		"literalInputId": {
			"dataType": {
				"name": "double"
			},
			"value": "0.05"
		},
		"boundingboxInputId": {
			"bbox": [
				51.9,
				7,
				52,
				7.1
			],
			"crs": "EPSG:4326"
		}
	},
	"outputs": {
		"literalOutputId": {
			"transmissionMode": "value"
		},
		"boundingboxOutput": {
			"transmissionMode": "value"
		},
		"complexOutputId": {
			"format": {
				"mediaType": "application/xml"
			},
			"transmissionMode": "value"
		},
		"complexOutputsId": {
			"format": {
				"mediaType": "text/plain"
			},
			"transmissionMode": "reference"
		}
	},
	"response": "document",
	"mode": "async"
}
```

**Comment by ghobona** [comment]
..or perhaps the properties complexInputId, complexInputsId, boundingboxInputId and literalInputId were meant to be implementation specific?

**Comment by bpross-52n** [comment]
Thanks Gobe, those are the actual identifiers of the inputs. We are using the additionalProperties mechanism of OpenAPI that allows implementers to use custom identifiers as property names. See here: [input.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/input.yaml). More on the dditionalProperties mechanism: [Dictionaries, HashMaps and Associative Arrays](https://swagger.io/docs/specification/data-models/dictionaries/)

**Comment by ghobona** [comment]
That's a very useful mechanism. Thanks @bpross-52n .
