### ISSUE TITLE
Minor typo: .doss

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#143]
There appears to be a typo [Section 7.1](http://docs.ogc.org/DRAFTS/18-062.html#_overview)

![Screenshot 2021-03-09 at 18 02 49](https://user-images.githubusercontent.com/18121038/110516725-deedaa00-8101-11eb-9f2d-1ce0b72e83bf.png)

**Comment by bpross-52n** [comment]
Fixed in #150
