### ISSUE TITLE
Delete "WPS REST/JSON Binding Part 1: Core" from OpenAPI definition document 1.0-draft.6-SNAPSHOT

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#144]
The description of the conformance path in the OpenAPI definition document mentions WPS. "WPS REST/JSON Binding Part 1: Core" should be deleted.

![Screenshot 2021-03-09 at 18 08 31](https://user-images.githubusercontent.com/18121038/110517305-971b5280-8102-11eb-9667-8dd302fd0017.png)

**Comment by bpross-52n** [comment]
I cannot find this in https://app.swaggerhub.com/apis/geoprocessing/ogcapi-processes/1.0-draft.6-SNAPSHOT#free
@ghobona Can you tell me where you found this?

**Comment by bpross-52n** [comment]
Anyway, this will be fixed by #146

**Comment by bpross-52n** [comment]
Fixed with commit 0760d0d
