### ISSUE TITLE
/api is missing from the OpenAPI definition document 1.0-draft.6-SNAPSHOT

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#145]
https://app.swaggerhub.com/apis/geoprocessing/WPS-all-in-one/1.0-draft.6-SNAPSHOT

**Comment by bpross-52n** [comment]
OGC API - Features states that there is no need to include the path to the API definition in the API definition itself, see here: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_operation_2 
I will take over this permission, as the text in the API - Processes standard already states the same.
