### ISSUE TITLE
Revise the description of the /conformance path in the OpenAPI definition document 1.0-draft.6-SNAPSHOT

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#146]
The description of the `/conformance` path is currently:

"list all requirements classes specified in a standard (e.g., WPS REST/JSON Binding Part 1: Core) that the server conforms to"

Please change to the following:

"A list of all conformance classes, specified in a standard, that the server conforms to."

**Comment by bpross-52n** [comment]
Fixed with commit https://github.com/opengeospatial/ogcapi-processes/commit/0760d0ddf21989ca82df4107852e5134d93977d5
