### ISSUE TITLE
Consider using "self" relation type for elements of /processes pointing to `/processes/{processId}`

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#149]
_OGC API - Features_ (and _Common - Part 2_) has established this pattern that elements of an array linking to a more complete version of the object use the `self` link relation type.

This seems to apply to elements of list of processes at `/processes` pointing to the full process description, and would replace the `process-desc` relation type (as well as the `execute` which is now the same?).

We have also settled on this approach at multiple places in other OGC API specifications (see those links identified by `[self]` in [Joan's graph](http://joanma.uab.cat/temp/graphs/OGCAPItiles.htm)).

In addition, this relation type would make more sense now that this link is not only a process description, but also the execute end-point as decided by #124.

**Comment by jerstlouis** [comment]
@bpross-52n Should this be tagged 1.0-Draft 6?

**Comment by bpross-52n** [comment]
Peter will create a PR for this.
