### ISSUE TITLE
inlineOrRefData.yaml is still referenced in result.yaml, however, inlineOrDataRef.yaml has been removed.

### ISSUE THREAD

**Issue by gardengeek99** [opengeospatial/ogcapi-processes#158]
inlineOrRefData.yaml is still referenced in result.yaml, however, inlineOrDataRef.yaml has been removed.

**Comment by pvretano** [comment]
Oopsie! All patched up.  Please review and close this issue if all is OK.

**Comment by gardengeek99** [comment]
Thanks for the quick turn around.  Schemas all seem to be in order now.
