### ISSUE TITLE
Remove the observedProperty key ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#166]
As agreed in the 28MAR2021 SWG meeting, the observedProperty key should be removed because it is out of scope for the core.

**Comment by gfenoy** [comment]
I would like to highlight that we agreed previously to add this observedProperty following feedbacks received from the previous input definition we provided.

**Comment by spacebel** [comment]
I think this property should be excluded from the core, and associated to a comformance class.

**Comment by gfenoy** [comment]
Sure, SWG agreed on Mars 28th, it was just a note.

**Comment by bpross-52n** [comment]
Should be fixed by #167
