### ISSUE TITLE
range.yaml still used?

### ISSUE THREAD

**Issue by bpross-52n** [opengeospatial/ogcapi-processes#173]
[range.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/range.yaml) is not used by any other schema and I also don't see external references. Should this be kept like bbox.yaml to give guidance?

**Comment by bpross-52n** [comment]
It is not used anymore. Can be removed.

**Comment by spacebel** [comment]
I agree:  if JSON schema is used, it would be expressed using minimum, maximum.

Note this doesn't support list of ranges.
