### ISSUE TITLE
execute.yaml misses the process id and version

### ISSUE THREAD

**Issue by spacebel** [opengeospatial/ogcapi-processes#175]
If I'm correct, the process id (previously in the request parameter) is missing as well as the (optional) version property.

**Comment by bpross-52n** [comment]
The id is in the path /processes/{processID}/execution. What version property do you refer to?

**Comment by spacebel** [comment]
From my knowledge, the reference api is at https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi.yaml ?

It states the execute operation path is /jobs ? (which seems to match with discussions I've seen on the mailing)

**Comment by spacebel** [comment]
The version is a required property from the process description (summary):  https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/processSummary.yaml

When executing the process, you shall be able to specify which version (if any) you wish to execute.

**Comment by bpross-52n** [comment]
I would use this requirement as reference: https://github.com/opengeospatial/ogcapi-processes/blob/master/core/requirements/core/REQ_job-creation-op.adoc
But thanks a lot for the hint, I will adjust the path in the openapi.yaml file! What version property do you refer to?

**Comment by spacebel** [comment]
The version property is a defined the process description (summary):  https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/processSummary.yaml

When executing the process, you shall be able to specify which version (if any) you wish to execute, otherwise, the property is useless in the process description.

EDIT: I just saw WPS 1.0 states this: "The processVersion is informative only. Version negotiation for processVersion is not available. Requests to Execute a process do not include a processVersion identifier."

I still believe it should either disappear from both, or appear in both. In my current projects, the versioning is critical.

**Comment by bpross-52n** [comment]
Feel free to create a new issue/change request for the version property. Note that on Monday the SWG decided on a feature freeze for version 1.0 of the API. The remaining change requests for this version can be found here: https://github.com/opengeospatial/ogcapi-processes/projects/1 
You may be happy to see most of your recent change requests will be considered for version 1.0.
