### ISSUE TITLE
Improve consistancy for the jobs ressources

### ISSUE THREAD

**Issue by christophenoel** [opengeospatial/ogcapi-processes#177]
Some months ago, the discussion was about to move or not the jobs endpoint to the root level versus keeping in processes.
I have probably missed the discussions that led to the current conclusion, but the result sounds not correct.

The managed REST resource is "jobs". So one can think of creating jobs with the REST endpoints **/processes/{processId}/jobs** (if this is the path of the jobs ressource) or **/jobs** ... But in any case, creating a /jobs through /processes/{processId}/execution is againt the REST philosophy.

Was it fixed for a critical reason ? I don't understand.

**Comment by bpross-52n** [comment]
Thanks for expressing your strong opinion. However, you might want to have a look at the [OGC Code of Conduct](https://www.ogc.org/ogc/policies/conduct).

The main reason to switch to the "../execution" endpoint was that synchronous execution does not create a job resource and therefore using a path including the word "jobs" was deemed misleading.

**Comment by spacebel** [comment]
Sorry I didn't intend to be mean.

**Comment by bpross-52n** [comment]
All good 👍

**Comment by jerstlouis** [comment]
@christophenoel @bpross-52n @pvretano 

Is it really necessary to mandate a specific path for job management?
I would prefer to leave that up to the server.

From a client's perspective, whenever you execute a job you get back a link to your job which allows you to cancel it or check its status.

I would prefer to leave it up to the server whether it wants to implement per process or global listing or jobs.
This way anyone with strong opinion one way or the other is happy.

What is really needed is a specific relation type for a "list of jobs".
That could be used from `/processes` or from `/processes/{processId}`, and could either link to the same global list, or to the process-specific list of jobs.

In fact servers could easily implement both `/jobs` and `/processes/{processId}/jobs`.

**Comment by fmigneault** [comment]
In our implementation, we do exactly as @jerstlouis said. Both `/jobs` and `/processes/{processId}/jobs` are implemented to essentially retrieve the same jobs. Both endpoints exist mostly for convenience, but I strongly believe that `/processes/{processId}/jobs` should be the preferred method. The reason I think so is that a job must *always* be related to some process, and therefore, REST philosophy would suggest that job items should be nested under processes to indicate that relationship. A `process` passed by body or query parameter via `/jobs` endpoint is a "hack".

Regarding the `/processes/{processId}/execution`, I can see how some servers could want to not implement jobs for sync processes (fair enough), but there must be some conformance indication that this server doesn't support them. When jobs are supported, I believe OGC should enforce their format and endpoints just to help users understand and familiarize with a common API structure. WPS processes and formats can be hard enough to understand by new users, better to have similar interfaces at the very least. As for implementation, we simply redirect `/processes/{processId}/execution` to `/processes/{processId}/jobs`, again for convenience purpose.

**Comment by pvretano** [comment]
@jerstlouis @fmigneau FYI this issue was raised more that a year ago (see #69).

**Comment by jerstlouis** [comment]
@fmigneault There is a [jobs list](https://docs.ogc.org/DRAFTS/18-062.html#_conformance_class_job_list) conformance class already in the current specifications.

But the specifications don't say anything about how long a job result should stay alive, and synchronous jobs may be many and cheap to re-execute. So in my opinion clients making a synchronous request should not rely on the jobs listing/management being available, and would not be expected to 'delete' a synchronous job to clean it up. Even without implementing jobs, a server could cache execution results for a quick response to a request identical to a recent previous one.

The jobs listing may also only be available for authenticated users, while some limited process execution capabilities may be available while note authenticated.

**Comment by fmigneault** [comment]
@pvretano  Indeed. 
And along those discussions, I have gradually updated our implementation to support most agreed variants, including the latest `/processes/{processId}/execution` in https://github.com/crim-ca/weaver/pull/242 (still pending). I don't mind whether this discussion leads to a change about execution path, as long as previously agreed jobs paths remain valid. 

@jerstlouis 
I agree that any job could be cached only momentarily, or even be wiped right after execution was completed once the user was able to retrieve its result. My point is more that there is no reason for a job object to exist unless it was associated to some process in the first place, so a RESTful reference to that job should be as `/processes/{processId}/jobs/{jobID}`. 

Our implementation supports `/jobs` as defined by that job-list conformance, and that makes senses only when "all jobs regardless of process" must be fetched. The situations that I refer to as a "hack" are when doing operations specific to a process, aka following should be **avoided**: 

`/jobs?process={processId}`
`/jobs`  body: `{ "process": "{processId}" }`

**Comment by christophenoel** [comment]
Very interesting.

Though, having a good path for the job execution would prevent us creating redirections each time someone define a new path, isn't it ? :)

**Comment by bpross-52n** [comment]
Please check the current specification and feel free to reopen the issue.
