### ISSUE TITLE
Small inconsistencies in the current documentation for transactions

### ISSUE THREAD

**Issue by gardengeek99** [opengeospatial/ogcapi-processes#179]
In extensions/transactions/standard/clause_6_transactions.adoc

Sequence diagram for modifyProcess, shows successful response of 200, but the following response section shows a 204.  I believe the sequence diagram should also show a 204.
Sequence diagram for undeployProcess shows successful response of 200, but the following response section shows a 204.  I believe the sequence diagram should also show a 204.

**Comment by pvretano** [comment]
@gardengeek99  Fixed.  Please review and close.
