### ISSUE TITLE
schema.yaml references schemaFull.yaml that doesn't exist

### ISSUE THREAD

**Issue by gardengeek99** [opengeospatial/ogcapi-processes#180]
https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/schema.yaml references schemaFull.yaml that doesn't exist.

**Comment by gfenoy** [comment]
Also, I think that in the same file on line 129, we should have a reference to ```schema.yaml``` like in the following:

````
         $ref: "schema.yaml"
````

I guess ```schemaFull.yaml``` should also be set to ```schema.yaml```.

**Comment by pvretano** [comment]
@gardengeek99 @gfenoy oops ... fixed now.  Please review and close the issue.

**Comment by gardengeek99** [comment]
Looks to be good now!  Thanks again for the quick turn around!
