### ISSUE TITLE
Unable to validate an OpenAPI based on the current "main" branch

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ogcapi-processes#190]
First, I do apologize if the way of validating I am presenting here is wrong in any way. Nevertheless, I was able to validate the published OpenAPI based on previous version of the "main" branch using this method before. 

The tool I traditionally use to validate our OpenAPIs is [openapi-cli](https://github.com/Redocly/openapi-cli). When trying to validate any of the previously published OpenAPIs relying on the "main" branch we were getting the following (the warning are relative to example from [ProcessDescription.yaml](https:/raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/responses/ProcessDescription.yaml) for 5 of them and the other warning is implementation specific):

````

[1] https:/raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/reference.yaml:4:1 at #/patternProperties

Property `patternProperties` is not expected here.

2 | required:
3 | - "$ref"
4 | patternProperties:
5 |   "^\\$ref$":
6 |     type: string

Error was generated by the spec rule.


❌ Validation failed with 1 error and 6 warnings.
````

As noted [here](https://swagger.io/docs/specification/data-models/keywords/) the patternProperties keyword is not supported by OpenAPI 3.0.

To be sure that the issue does not come from the tool we were commonly using to validate our OpenAPIs, we moved to [spectral](https://stoplight.io/open-source/spectral/) but, we did not have more luck in validating with it. The summarized result of the validation was the following (warnings were about the tags defined in our API without the presence of a global tags array containing the list of all the tag names used, so implementation specific again):

````
https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/examples/json/ProcessDescription.json
 1:1  error  invalid-ref  OpenError: Page not found: https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/boundingBoxData.json  inputs.boundingBoxInput.schema.$ref
 1:1  error  invalid-ref  OpenError: Page not found: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/geometryGeoJSON.json                           inputs.geometryInput.schema.items.oneOf[1].$ref

https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/responses/ProcessDescription.yaml
 4:12  error  oas3-schema  Property `patternProperties` is not expected to be here.  content.application/json.schema

✖ 14 problems (3 errors, 11 warnings, 0 infos, 0 hints)
````

First we note that the same issue about patternProperties is present with that tool. For the other errors they are simply typo in the provided URIs.

To solve these issues, I have made the PR #187. If we don't have any error, 5 warnings are still remaining when using openapi-cli tool (about example as quoted before).

Nevertheless, even if the APIs were now validating by using the mentioned tools, we were still unable to access the ProcessDescription due to recursive use of schema.yaml I suppose. By removing these references to schema.yaml within then the swagger-ui was working again and the validation was passing. I made a PR #189 corresponding to this modification. I also have found a small fix that seem to work as expected for the example provided in the ProcessDescription by renaming it to examples and change a bit the syntax. Anyway, I am not sure about this modification but I made it to have no warnings from openapi-cli nor spectral when referring the "main" branch.

I understand the relevance of the schema.yaml content as it was before I made these changes and I understand clearly why we are using the definitions this way and recursively but, I was unable to find another way around to get the swagger-ui working except by removing these parts that sounds relevant.

I will continue to work on this issue and hope to come back with a better solution.

**Comment by bpross-52n** [comment]
Fixed.
