### ISSUE TITLE
The /jobs endpoint should be extended with a set of query parameters to allow filtering of jobs 

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#209]
The `/jobs` encoding should be extended with a set of query parameters to allow filtering of the jobs reported there.  
```
/jobs?processID=id1
/jobs?processID=id1,id2,id3
/jobs?datetime=2021-06-08T01:13:54Z/2021-06-08T07:33:00Z
```
A proposed set of query parameters might be:
- processID -> list of one or more process id.
- status -> list of one or more status tokens
- datetime -> specific date or date range

With regard to `datetime`, which date should it target from the status info (created, started, finished, updated)?  ... or should we have one query parameter per type of date?

**Comment by jerstlouis** [comment]
@pvretano being able to filter on any type of dates makes a lot of sense to me

**Comment by pvretano** [comment]
@gardengeek99 proposed we also add limit and count to the `/jobs`/ endpoint for paging which I think is a good idea.

**Comment by gardengeek99** [comment]
I think if we keep the query parameters as close to the StatusInfo as possible, it makes server implementation easier.

**Comment by fmigneault** [comment]
We just recently implemented the `datetime` support for CRIM's implementation to do exactly as proposed. 
https://github.com/crim-ca/weaver/issues/236
We decided to align `datetime` with `created` because it made more sense in our opinion, since the user that started the job usually has a good idea of when he submitted it, but not really when it was actually started/completed.

If possible, I would like to have `processID` replaced by only `process` that we also support already. 

I also agree with @jerstlouis for a `type=process` is very useful. 
In our case, we use instead `groups=process,service,provider` to combine different kinds of WPS remove provider or local processes, but the idea is the same. 

I would also consider filtering by other execution methods (sync vs async).

Paging with `limit` and and `page` is an excellent addition when the job list becomes long, if not a requirement for better response times by the API. 

We also have other fields which you can get additional inspiration from: 
https://pavics-weaver.readthedocs.io/en/latest/api.html#tag/Jobs/paths/~1jobs/get 
For example: `sort` that tells by which field the jobs should be sorted by, and `order` for ascending/descending. 

Another thing we have been thinking about is also the possibility of generic `q=` query approach, where more advanced queries could be provided (eg: natural language search or regex matches of process metadata/abstract). 
More ideas here: https://github.com/crim-ca/weaver/issues/102

**Comment by pvretano** [comment]
@fmigneault CQL?

**Comment by jerstlouis** [comment]
@fmigneault & @pvretano how about `filter` and `filter-lang` which could default to CQL :)

**Comment by pvretano** [comment]
@jerstlouis that is what I meant by CQL.  Sorry I thought it was understood that you need to bind WPS to CQL via the use of filter, filter-lang, etc.  ... which of course means you can also use other filter languages but that would not be described in the specification since we would want a standard filter language.

**Comment by cristianoManuelLopes** [comment]
CQL could be an extension... don't know if we could have something simpler in the core?!

**Comment by pvretano** [comment]
@cristianoManuelLopes I was just exploring what use cases would fall out if we support CQL.  Personally I think that, for the purpose of filtering status objects from the `/jobs` endpoint, CQL is probably a little bit of overkill.  As concise set of query parameters should be sufficient for the core I think ... So far, I believe the list looks like this:

1. limit, count (for paging)
2. type
3. processID
4. status
5. created,started,finished,update OR datetime (still thinking about this one)

The other parameters discussed (filter with CQL, sort, etc.) are nice to have but not essential in the core I think.

**Comment by gardengeek99** [comment]
How about duration?  Give me all jobs that took longer than...
It would probably be much easier for the server to handle this.

**Comment by fmigneault** [comment]
I was thinking about something not as advanced as CQL, but that could also be an option. 
As @cristianoManuelLopes said, that would need to be defined as an extension because it won't be reasonable to expect every core implementation to support it.

**Comment by bpross-52n** [comment]
Peter will create a PR for this.

**Comment by pvretano** [comment]
@gardengeek99 how would duration be computed?  {/jobs request time}-started?

**Comment by jerstlouis** [comment]
@pvretano I think there are two types of duration...

- age (useful for incomplete jobs):  current time - request time
- run duration (useful for completed jobs): completed time - start time

+1 for seconds

**Comment by fmigneault** [comment]
Duration (and similar variants) seems not that useful in my opinion, unless they can be defined in combination with comparators (`>`. `<=`, etc) to help searching for ranges.
To search jobs, I usually tend to use `status=running` or `status=accepted,running` instead.
It is much easier and reusable than specific duration values.

**Comment by jerstlouis** [comment]
@fmigneault considering this extension is following the filtering approach, the core conformance class for CQL supports operator comparisons, and I think that it would be very useful to filter e.g. jobs that took longer than 5 minutes to run.

**Comment by fmigneault** [comment]
@pvretano  @jerstlouis  
This is why I believe `duration` is not that useful in itself. 
If a request is done with `duration=100` (assuming seconds unit), that means that jobs would be listed only when hitting that very specific duration?

**Comment by jerstlouis** [comment]
@fmigneault I fully agree that `duration=` is a useless capability, so it only makes sense to define it in the context of a filtering extension that supports comparisons.

**Comment by pvretano** [comment]
I think that @gardengeek99 original request for duration was: _"Give me all jobs that took longer than..."_.  So the definition of the parameter would say something like: the value of the duration parameters identifies the set of jobs that have (a) been running for at least X seconds and (b) the set of jobs that took at least X seconds to run.  So, saying duration=100 means: 
- find all completed jobs that took 100s or longer to run
- find all running jobs that have been running for 100s or longer

@gardengeek99 did I get that right?

If yes, then there is no need for comparison operators.

**Comment by jerstlouis** [comment]
@pvretano That feels confusing and arbitrary to me. What if I am interested to know the jobs that took _less_ than 100 seconds instead? We should use _minDuration_ and _maxDuration_ instead if we really want a simple parameter without operators.

**Comment by pvretano** [comment]
@jerstlouis then you use the supper dupper CQL-base job filtering extension (something that is out of scope at this time).  What I think @gardengeek99 is requesting here is a simple, useful, duration filtering capability.  It seems to me that identifying long-running jobs might be a useful first-level capability ... but I am also happy to leave the parameter out if people don't agree.

**Comment by jerstlouis** [comment]
@pvretano _minDuration_ and _maxDuration_ seems to perfectly handle @gardengeek99 's scenario without the ambiguity and without the super-duper CQL capabilities :)
This way you can easily find the jobs that took between 5 and 20 min with `&minDuration=300&maxDuration=1200`.

**Comment by pvretano** [comment]
@jerstlouis again, the use case seems to be to identify long running jobs and a single parameter seems to do the jobs.  No?

**Comment by jerstlouis** [comment]
@pvretano _maxDuration_ then? :) `duration=` is not self-explanatory/intuitive.

**Comment by pvretano** [comment]
@jerstlouis since you are looking for jobs that took "at longer than ..." wouldn't the appropriate parameter be minDuration?

**Comment by jerstlouis** [comment]
@pvretano Yes, my bad sorry. Kind of tangling myself up in my own argument here ;)

**Comment by pvretano** [comment]
@jerstlouis LOL!
