### ISSUE TITLE
Possible invalid result reference

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#219]
Following requirement: 
https://github.com/opengeospatial/ogcapi-processes/blob/master/core/requirements/core/REQ_job-creation-success-sync-document.adoc
indicates that 
https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/results.yaml 
must be returned as `application/json`. 
Same applies for async that redirect to above sync requirement.

The `results.yml` schema tells the JSON content can be either an literal value, a link, an object with `value` field, or an array of any of the previous items. This makes sense when 1 output is expected, but how can one identify which output is which when multiple ones can be returned? 

Previously, we had the following: 
```json 
{
  "output1": { "href": "http://link", "format": "application/json" }, 
  "output2": {  "value": 1 }
}
```

It feels this format should also be possible in place of `results.yml` directly in the body without the output ID.

**Comment by pvretano** [comment]
@fmigneault [results.yaml](https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/results.yaml) indicates that multiple result are an array of values.  Arrays are ordered no?I believe the intent was to have the values in the array be in the order requested in the execute request .. or the order defined in the process description of the outputs key was left off the request (indicating "give me all defined outputs").  I'll check the specification to see if it says anything about that.  If not, I will add a requirement for that ...

**Comment by fmigneault** [comment]
Probably the array of values that can now be directly provided inline will conflict with a single `id` but `maxOccurs>1` vs >1 output `id` each with `maxOccurs=1`. There would also be problematic handling with nested array if `maxOccurs>1` AND more than one output `id` is expected. 

Technically, nothing ensures the index position of an output key from the process description `outputs` mapping to match the index in the result as array. 
A long time ago, process description was providing
```
{
  outputs: [ 
    { "id": "output-1" }, 
    {"id": "output-2"}, ... 
  ]
}
```
but since this has been modified to be 
```
{
  outputs: { 
    "output-1": { ... },
    "output-2": { .. }
  }
}
```
There is no array index available anymore to map against.

**Comment by pvretano** [comment]
@fmigneault ignore everything I said.  I was distracted and thinking of something else.  

I checked the specification and the `results.yaml` schema is this:
```
additionalProperties:
  oneOf:
    - $ref: "inlineOrRefData.yaml"
    - type: array
      items:
        $ref: "inlineOrRefData.yaml"
```
and the response example in the specification looks like this:
```
{
  "stringOutput": "Value2",
  "measureOutput": {
    "value": {
      "measurement": "10.3",
      "uom": "m",
      "reference": "https://ucum.org/ucum-essence.xml"
    }
  },
  "dateOutput": "2021-03-06T07:21:00",
  "doubleOutput": "3.14159",
  "arrayOutput": [1,2,3,4,5,6],
  "complexObjectOutput": {
    "value": {
      "property1": "value1",
      "property2": "value2",
      "property5": true
    }
  },
  "geometryOutput": [
    {
      "value": "<gml:Polygon gml:id=\"GID1\" srsName=\"urn:ogc:def:crs:OGC::CRS84\"><gml:exterior><gml:LinearRing><gml:posList>-77.024519 38.810529 -77.024635 38.810973 -77.024704 38.810962 -77.024776 38.811239 -77.024957 38.81121 -77.024905 38.811012 -77.024905 38.811012 -77.024865 38.810857 -77.025024 38.810832 -77.025071 38.811012 -77.025203 38.810992 -77.02506 38.810444 -77.024519 38.810529</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon>",
      "mediaType": "application/gml+xml; version=3.2"
    },
    {
      "value": {
        "type": "Polygon",
        "coordinates": [[[ -176.5814819,-44.10896301 ],
                         [ -176.5818024,-44.10964584 ],
                         [ -176.5844116,-44.11236572 ],
                         [ -176.5935974,-44.11021805 ],
                         [ -176.5973511,-44.10743332 ],
                         [ -176.5950928,-44.10562134 ],
                         [ -176.5858459,-44.1043396  ],
                         [ -176.5811157,-44.10667801 ],
                         [ -176.5814819,-44.10896301 ]]]
      }
    }
  ],
  "boundingBoxOutput": {
    "bbox": [51.9,7,52,7.1],
    "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
  },
  "imagesOutput": [
    {
      "href": "https://www.someserver.com/ogcapi/Daraa/collections/Daraa_DTED/styles/Topographic/coverage?...",
      "type": "application/tiff; application=geotiff"
    },
    {
      "value": "VBORw0KGgoAAAANSUhEUgAABvwAAAa4CAYAAABMB35kAAABhGlDQ1BJQ0MgcHJvZmlsZQAA\nKJF9kT1Iw0AcxV9TpSL1A+xQxCFDdbIgKuKoVShChVArtOpgcumH0KQhSXFxFFwLDn4sVh1c\nnHV1cBUEwQ8QNzcnRRcp8X9JoUWMB8f9eHfvcfcOEOplplkdY4Cm22Y6mRCzuRUx9IogouhH\n ... \nj3Z5mX7/PCPVRJV92rpHK24xcJrzk20+tkeYlCPqcZNO3Lpni1OJWatPCcmgGDEqx7Om6lfa\nppM4k4BTe9+bsn3L9/9/yWhA0PwQGW8ipCZsnZt9lsdrYEM8z/M8z/M8z/M8z/M8z/MzLWY1\nAAAACUlEQVQ871H6P6JI+TxS5Wn2AAAAAElFTkSuQmCC",
      "encoding": "base64",
      "mediaType": "application/tiff; application=geotiff"
    }
  ],
  "featureCollectionOutput": {
    "value": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><FeatureCollection xmlns=\"http://schemas.myserver.com/namespaces/null\" xmlns:gml=\"http://www.opengis.net/gml/3.2\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://schemas.myserver.com/namespaces/null https://www.pvretano.com/myserver/ogcapi/daraa/schema?f=GML32&amp;collectionids=TransportationGroundCrv http://www.opengis.net/gml/3.2 http://schemas.opengis.net/schemas/gml/3.2.1/gml.xsd\">...",
    "mediaType": "application/gml+xml; version=3.2"
  }
}
```

Ok, can you point me there where the issue is using this schema and this example as a reference?

**Comment by jerstlouis** [comment]
@fmigneault @pvretano 
I think the confusion is that the results is a map/dictionary/_associative_ array, like in the outputs descriptions, as indicated by the `additionalMembers`.

The `type: array` there seems to have been copied from the _input_ description which have multiplicity.
However, according to https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/outputDescription.yaml there is no multiplicity for outputs.

So I think the _results.yaml_ should be simply:

```yaml
additionalProperties:
 - $ref: "inlineOrRefData.yaml"
```

**Comment by fmigneault** [comment]
Ah yes. @jerstlouis is right. 
Confusion on my part with the `additionalProperties` that represents the output ID.

It is valid though that either `inlineOrRefData` or an array of them be under that ID. 
Otherwise, output cannot be something like so: 
```json 
{
  "output_links": [
    "https://first-link.nc",
    "https://second-link.nc"
  ]
}
```

**Comment by pvretano** [comment]
@fmigneault if you think the issue is resolved, please close.  Thanks.

**Comment by jerstlouis** [comment]
@pvretano 
There is still an actual issue in [results.yaml](https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/results.yaml)

Each output is a single output as described in the JSON schema.
If the output is defined as an array as per @fmigneault 's example, that can still be done by declaring the [schema](https://github.com/opengeospatial/ogcapi-processes/blob/e49259b673a9b5eacfccbf0f491fbb11eab916f6/core/openapi/schemas/outputDescription.yaml#L7) to be an array.

**Comment by pvretano** [comment]
@jerstlouis I see you created a PR (thanks for that) so we can just leave this closed.  Once we merge it would be closed anyway.
