### ISSUE TITLE
'dismiss' is not defined in the jobControlOptions

### ISSUE THREAD

**Issue by jonherrmann** [opengeospatial/ogcapi-processes#221]
Please see:
https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/jobControlOptions.yaml 

and the example: https://github.com/opengeospatial/ogcapi-processes/blob/master/core/examples/json/ProcessList.json

Discussed in the T17 CITE meeting with Peter and Gérald.

**Comment by pvretano** [comment]
dismiss is already in jobControlOptions.yaml in the master so we can close.
