### ISSUE TITLE
jobControlOptions.yaml should not have a default

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#224]
I'm not sure it is correct to have a "default" in jobControlOptions.yaml.

This particular schema only appears in the process description's list of available jobControlOptions as an array, where there really is no default -- every supported control option must be explicitly listed.

There also isn't really a default execution mode (and this is more than about execution modes too -- dismiss is not an execution mode).
Sync execution is only default if the server does advertise sync-execute and no _Prefer:_ header is used.

**Comment by pvretano** [comment]
@jerstlouis I agree.  In this context it does not make much sense to have a default value.  I'll create a PR to fix.
