### ISSUE TITLE
Specification housekeeping (all editorial changes).

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#231]
This purpose of this issue is just as a reminder that we need to do some specification housekeeping.  For example, the clause .adoc file names are all over the place ... clause_7_core.adoc, clause_7c_security-considerations.adoc, etc.  Also, the files names for the requirements classes do not, in some cases, reflect what the requirement is about so we should rename these just to make document maintenance a little easier.
Most of this stuff can only be done once we decide to got for an adoption vote but before we present the document to the TC.
This is mostly a reminder for @bpross-52n and me to do the work.

**Comment by bpross-52n** [comment]
The example in 7.2.2. has a wrong link-relation. 
IS http://www.opengis.net/def/rel/ogc/1.0/jobs-list 
SHOULD BE http://www.opengis.net/def/rel/ogc/1.0/job-list

**Comment by bpross-52n** [comment]
My colleague also said that it would be good to add the parameters for the /jobs and /processes endpoint would be added to the OpenAPI spec, instead of just be stated in the text.

**Comment by bpross-52n** [comment]
Update document history... this will take me a loooong time, thanks Jerome and Peter :D
