### ISSUE TITLE
Are `finished` and `updated` not redundant?

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ogcapi-processes#232]
Looking at the [statusInfo](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/statusInfo.yaml) definition, I wonder if there is not two different attributes to store the exact same information (namely: `finished` and `updated`).

With my understanding, when the `status` takes one of these values: `successful`, `failed`, `dismissed`, then `updated` field will take the exact same value as `finished`. So the server will have to output twice the same information in different attributes. 

The client applications should also be able to deal with only the `updated` attribute and the `status` value. Even if it is optional currently, I would prefer we don't mention this field in the draft specification.

**Comment by pvretano** [comment]
@gfenoy I don't think they are redundant. 

 In my server everything is run in Docker containers.  The `started` and `finished` time reflect the time the Docker container started running and finished running.  These times are different than the `created` and `updated` times which reflect the time the execute request was created in the processes server and the time it was last updated. 
 The `started` and `finished` time do not, not example, take into account the time it takes for server to set up the execution environment, to stage the inputs and then copy the output to the output cache, etc.  Generally the `started` time > `created` time and the `finished` time > `updated` time.

**Comment by gfenoy** [comment]
Thanks for the clear explanation, I do understand.
