### ISSUE TITLE
Is processID in statusInfo really optional?

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ogcapi-processes#233]
I just would like a confirmation that the processID is optional in [statusInfo](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/statusInfo.yaml) definition?

It is defined as optional now, but I wonder if it should not be in the list of the required ones. 

Indeed, when we moved the job management to the `/jobs` path, we lost the `processID` from the path and I think it was the reason why we added this `processID` attribute to the `statusInfo`. If so, then, we should probably make it a required attribute.

Without the `processID` required in statusInfo, it may become difficult to handle job filtering per `processID`. I mean, how the client application will be able to know what are the processID that can really be used? (server implementation can have a dedicated process returning a `processID` array or add a specific end-point for this but, I think it would be good to make it a required field).

**Comment by pvretano** [comment]
Doh!  @gfenoy I forgot to make it mandatory if the server supports the Job List conformance class.  I created a quick PR to fix that.
