### ISSUE TITLE
Require documentation of OGC requirement structure

### ISSUE THREAD

**Issue by opoudjis** [opengeospatial/ogcapi-processes#239]
Metanorma has an opinionated structure of requirements, and we have implemented some attributes to address OGC's needs, but there are clearly instances of structure here that are novel to us, and we will need to understand them before we can encode them in Metanorma. 

In particular:

1. Apparent sub-requirements.

It appears that you have clauses embedded within your requirements, that are rendered on separate rows, and that are introduced by an alphabetic letter. e.g.

https://github.com/opengeospatial/ogcapi-processes/blob/91121176dbb3b4241bc221767fb3ae886c2216ca/core/recommendations/core/REC_job-status.adoc

* Are these subrequirements embedded in a requirement, or something else?
* Is there a rationale differentiating requirements where the text is inline with the definition, vs requirements where the text forms a single subrequirement? e.g. https://github.com/opengeospatial/ogcapi-processes/blob/91121176dbb3b4241bc221767fb3ae886c2216ca/core/recommendations/core/REC_html.adoc vs https://github.com/opengeospatial/ogcapi-processes/blob/91121176dbb3b4241bc221767fb3ae886c2216ca/core/recommendations/core/PER_process-list-prev.adoc
* If the letters are subrequirement identifiers, are they ever cross-referenced individually from elsewhere?
* Is there a reason that the letters are in a non ascending sequence of A, A, B, C in https://github.com/opengeospatial/ogcapi-processes/blob/91121176dbb3b4241bc221767fb3ae886c2216ca/core/recommendations/core/REC_job-status.adoc, or is this deliberate? 

2. Components

Individual components of requirements are recognised by Metanorma, but they are recognised according to a preset vocabulary of labels; Metanorma currently supports the components "verification", "measurement-target", and "specification" as generic requirement components. 

Your requirements are presenting what appear to be components of requirements, identified in the first column as such, but we have not seen these before, so we do not recognise them. We have seen so far Conditions, Test Purpose, Test Method.

* Is there a fixed list of what these are in OGC?
* Is there documentation of what these mean?

3. Cross-references to requirements

We note that a requirement includes a row with "Requirement" introducing a crossreference. This also occurs in Conformance Class requirements, crossreferencing a Requirement Class.

* What is the purpose of cross-references between requirements? Subclass? See also? Subject matter? We note that we have already implemented `Inherit`, so that can't be it. We have already encoded `Dependency`: how are they distinct from that?

This is a blocker to further work on https://github.com/metanorma/ogcapi-processes/issues/1

**Comment by ghobona** [comment]
@opoudjis Regarding Question 1 (Apparent sub-requirements).

The approach that we have used in another Metanorma-based OGC standard is below.

```txt

[[req_collections_src-md-success]]

[requirement,type="general",id="/req/collections/src-md-success", label="/req/collections/src-md-success"]
====
*A:*

A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.

---

*B:*

The content of that response SHALL be based upon the schema link:http://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/collection.yaml[collection.yaml].

---

*C:*

The content of that response SHALL be consistent with the content for this resource collection in the ``/collections`` response. That is, the values for ``id``, ``title``, ``description`` and ``extent`` SHALL be identical.

====


```

This renders in HTML as shown below.

<img width="873" alt="Screenshot 2021-07-30 at 13 24 40" src="https://user-images.githubusercontent.com/18121038/127652566-e968ad53-483e-4f90-96b1-07fcac0c2481.png">


And renders in PDF as shown below.

<img width="685" alt="Screenshot 2021-07-30 at 13 26 01" src="https://user-images.githubusercontent.com/18121038/127652703-771a03de-6ee0-4c6a-8565-78b013b1eeac.png">

**Comment by ghobona** [comment]
Regarding nested questions under Question 1:

Q: _Is there a rationale differentiating requirements where the text is inline with the definition, vs requirements where the text forms a single subrequirement?_

A: I could not see the difference in the format of the Permission and the Recommendation examples provided. Let's clarify that one over a telecon.

Q: _If the letters are subrequirement identifiers, are they ever cross-referenced individually from elsewhere?_

A: In most cases, the reference is a hyperlink to the Requirement and not the sub-requirement.

Q: _Is there a reason that the letters are in a non ascending sequence of A, A, B, C in [example](https://github.com/opengeospatial/ogcapi-processes/blob/91121176dbb3b4241bc221767fb3ae886c2216ca/core/recommendations/core/REC_job-status.adoc), or is this deliberate?_

A: This is a typo. 'A' should not be duplicated.

**Comment by opoudjis** [comment]
> Regarding nested questions under Question 1:
> 
> Q: _Is there a rationale differentiating requirements where the text is inline with the definition, vs requirements where the text forms a single subrequirement?_
> 
> A: I could not see the difference in the format of the Permission and the Recommendation examples provided. Let's clarify that one over a telecon.

Well, we'll have to book one then, but there's no A in the first, and there is an A in the second.

In any case, I think I know what do there, but it will be different to before: it will be a notion of subpart, marked up as a distinct open clause, the way Conditions will be. The A B C letters will be autogenerated. Are the subrequirements always distinct from things like Conditions, or can Conditions apply to specific subrequirements?

**Comment by ghobona** [comment]
@opoudjis It's unclear what 'Conditions' means in this context.

If you mean 'Conditions' as in _if....else if...else.._ statements, then the sub-requirements are distinct from things like Conditions.

I'm copying in the editors of the spec. @bpross-52n @pvretano  in case they have a different view.

**Comment by opoudjis** [comment]
>  It's unclear what 'Conditions' means in this context.

And of course, I don't know what I don't know :-)

I am referring to instances such as

https://github.com/opengeospatial/ogcapi-processes/blob/91121176dbb3b4241bc221767fb3ae886c2216ca/core/recommendations/core/REC_core_process-execute-sync-document-ref.adoc

To explain where I am going with all this:

You have tabular representations of requirements, which we are rendering in a machine readable form, with semantic enrichment. That means that everything in the left column of the tables has to be accounted for semantically by us, so we can render it and semantically mark it up appropriately. We don't need to understand this instance of Conditions deeply, but we do need to understand its possible scope (as you've just clarified), and what kind of things other than Conditions and letter-labelled subrequirements can turn up on the left-hand side in a requirement. 


We have accounted for the following to date in our encoding: Inherits, Target Type/Subject, Obligation, Dependency, and key/value Classifications.

You have just clarified the scope of Conditions, and thank you for that.

**Comment by opoudjis** [comment]
If this gets too much by the way, happy to have a teleconference, but I think it best to wait until @manuel489 finishes going through the corpus of recommendations in this standard. Perhaps some time next week?

**Comment by pvretano** [comment]
@ghobona @opoudjis it means that in order for this requirement to apply the condition(s) specified in the requirement must be met first.  We inherited this form from OGC API Features which also uses conditions.

Look at this [requirement](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/requirements/core/REQ_process-execute-success-sync-raw-mixed-multi.adoc).  The conditions are:

1. The negotiated execution mode is synchronous, response=raw,
2. Multiple transmission modes (value,reference) are requested.
3. The number of requested outputs is more than 1.

These are all conditions on the execute request (since this is a requirement for successful execution i.e. response) and they must all be met for this requirement to apply.  In order words, the execute request must be synchronous and the requested response mode must be raw and the number of output requested must be greater than one and multiple value transmission modes must be requested in the execute request.

Clear as mud? ;)

We borrowed this for _OGC API Features_ which also uses conditional requirements.

**Comment by ghobona** [comment]
@opoudjis 

Once @manuel489 finishes going through the corpus of recommendations, we will arrange a telecon.

**Comment by opoudjis** [comment]
Question 3 is open: whether "Requirement" and "Requirement Class" are distinct from "Inherit", and whether the labels "Requirement" and "Requirement Class" are completely predictable based on what they are pointing to.

@manuel489 has just finished going through his corpus. I'm going to do a base level implementation of the obvious aspects of OGC requirements structure:

* Condition, Test Method, Test Purpose, Part
* Autonumbering of Part with capital alphabetic numbering

I will then try and make sense of what else Manuel has found. Any time from Wednesday on is good.

**Comment by opoudjis** [comment]
OK, closing this ticket, but now that I understand ModSpec better, and have seen the example of https://docs.ogc.org/is/18-058/18-058.html#ats, I am going to be refactoring our treatment of OGC requirements, as I've communicated. This will result in a major version upgrade of metanorma-ogc, to 1.4.0, since it will not be (fully) backward compatible.
