### ISSUE TITLE
Change request for the OGC Application Package CWL conformance class

### ISSUE THREAD

**Issue by p3dr0** [opengeospatial/ogcapi-processes#258]
This change request is to add CWL as a possible encoding of the Application Package. 

As we discussed in the last SWG telco the CWL encoding is not mandatory but an conformance class that the serves announces. 

The CWL application package was introduced in the best practice for EO Apps [OGC 20-089r1] and the transaction extension would be the right place to evolve.

Nevertheless, we should define an abstract information model that could come of the discussion on #176 or in a separate change request.

**Comment by pvretano** [comment]
@p3dr0 @fmigneault can you please review PR #382 and let me know if that PR closes this issue?

**Comment by p3dr0** [comment]
yes, all good I think we can close this issue
