### ISSUE TITLE
Possible incorrect schema for minDuration/maxDuration parameters

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#261]
Regarding schema: 
https://github.com/opengeospatial/ogcapi-processes/blob/6233fcd75dc9d2b97bf0a962b0243f20640950ea/core/openapi/parameters/minDuration.yaml
https://github.com/opengeospatial/ogcapi-processes/blob/6233fcd75dc9d2b97bf0a962b0243f20640950ea/core/openapi/parameters/maxDuration.yaml

Both use `type: array`. 
I am wondering if this is not an error? Or it is used for some motive that is not clear in the specification.

Reading the descriptions, a single value always seems to be expected for each parameter: 
https://github.com/opengeospatial/ogcapi-processes/blob/4e7714aac498ea71265d401cc34d1b8c4d78d1bc/core/abstract_tests/job-list/ATS_duration-response.adoc

Furthermore, I don't understand what would be the advantage or how to handle multiple values. 

For example, `minDuration=10,20&maxDuration=30`. 
It should return both jobs between (10, 30) seconds, and (20, 30) seconds. 
This is redundant because one set is completely contained by the other.

**Comment by pvretano** [comment]
@fmigneault good question ... don't remember so I will have to go back to the issue that made the initial proposal and review.

**Comment by bpross-52n** [comment]
Fixed in the current draft.
