### ISSUE TITLE
Extra spaces part of conformance class identifiers in Test Methods for AT 41, 43 & 44

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#270]
In [A.2.6.3](http://docs.ogc.org/DRAFTS/18-062.html#_job_results_jobsjobidresults):

> If the link exists, get the job status as per test /conf/**cor e**/job-op

3 separate occurrences in _Abstract Tests 41_, _43_ and _44_

**Comment by pvretano** [comment]
Fixed in master.
