### ISSUE TITLE
bbox schema enum restricted to CRS84 and CRS84h

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#317]
There is no point in having a `crs` in the [bbox schema](https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/bbox.yaml), or even this complex bbox object, if it can only be those 2 values, which can be inferred from whether there are 4 or 6 values in the array.

It could be made an `anyOf` including the enum or a `string` with a `format: uri` instead to allow for specifying a BBOX in other CRSes in some implementations.

**Comment by bpross-52n** [comment]
2023-04-17 SWG telecon: @jerstlouis will create a pull request for this issue.
