### ISSUE TITLE
Inconsistent schemas in DRU extension since OpenAPI restructure

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#319]
Since #306, both of these files exist at the same time:
- https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/deploy_replace_undeploy/standard/openapi/schemas/ogcapppkg.yaml
- https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/processes-dru/ogcapppkg.yaml

Although their names are the same, their contents are entirely different.

Multiple other items under https://github.com/opengeospatial/ogcapi-processes/tree/master/extensions/deploy_replace_undeploy/standard/openapi have not been moved at all. 

Having both locations with inconsistent schemas makes it very confusing for referencing this extension.

**Comment by jerstlouis** [comment]
@fmigneault @gfenoy 

When I worked on #306, I updated all of the reference from Processes - Part 1, but not those from Part 2.
That is why I left the schemas in Part 2 until it is updated properly.
I am not sure what the ogcapppkg in the root openapi directory is -- it might be the updated one from Gerald.
Gerald could you please verify and do a PR to update Part 2 to reference the new one, and remove the old schemas once everything works fine?

Note that the top-level metanorma document for Part 2 will have to be moved to the root alongside Part 1 & 3 to avoid errors referencing above it.

**Comment by gfenoy** [comment]
@fmigneault thanks for your patience.

The schemas should now be correct in the root openapi location [62f3743](https://github.com/opengeospatial/ogcapi-processes/pull/327/commits/62f374335fd5deb5838052107afb6123cb1959ef). Also, I have modified the [ogcapi-processes.yaml](https://github.com/GeoLabs/ogcapi-processes/blob/feature/fix-issue-319/openapi/ogcapi-processes.yaml) to include Part 2, but did not push the generated json bundle yet.

**Comment by fmigneault** [comment]
@gfenoy 
No problem. Thanks for working on this!

Would it be possible to include the `application/cwl`, `application/cwl+json` and `application/ogcapppkg+json` Content-Types for Deploy body as well to support the use-cases defined in these references?
- https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/deploy_replace_undeploy/standard/recommendations/deploy-replace-undeploy/deploy/REC_body-cwl.adoc
- https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/deploy_replace_undeploy/standard/recommendations/deploy-replace-undeploy/deploy/REC_body-ogcapppkg.adoc 
- https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/deploy_replace_undeploy/standard/recommendations/ogcapppkg/REC_ogcapppkg_execution-unit-cwl.adoc

**Comment by gfenoy** [comment]
@fmigneault it defenetely makes sense to add these content types, so I added them [24077f6](https://github.com/opengeospatial/ogcapi-processes/pull/327/commits/24077f6e5921cc17e8a6d4b112df7f41935e5e70).

As @jerstlouis said in this [comment]https://github.com/opengeospatial/ogcapi-processes/pull/327#issuecomment-1568291388) implementers can then comment content-tyes not supported. Note that, on case there is only one content-types remaining, then the `oneOf` should also be removed, I think.

**Comment by gfenoy** [comment]
@fmigneault an updated version is available here: https://github.com/GeoLabs/ogcapi-processes/commit/26e325bb9c58e4aa3c01f975cf26561d97fc8563. We are now able to have the select list for Deploy and Undeploy from there https://app.swaggerhub.com/apis/ZOO-Project/the-zoo_project_wps_ogc_api_processing_development_server/0.1#/. Still, there is this error when you select it, probably due to the wrong example we inserted to fake an empty object to get to select list...

To be continued.

**Comment by fmigneault** [comment]
@gfenoy 
If you feel like providing a detailed schema, I have it for CWL here: https://services.crim.ca/weaver/api#/Deploy/post_processes 
(JSON schemas somewhere under https://services.crim.ca/weaver/json definitions). 

Otherwise, a minimalistic CWL schema could be defined. Minimally, it has `"cwlVersion": "v{SEMVER}"` at the root that distinguishes it from other deploy body contents.

**Comment by gfenoy** [comment]
@fmigneault it seems you read my mind. Indeed, I am searching for the schema of the application/cwl+json but I am unable to find any official one unfortunately.

On the other hand, I have worked on this new version here: https://app.swaggerhub.com/apis/ZOO-Project/the-zoo_project_wps_ogc_api_processing_development_server/Part-2-Deploy-Replace-UndeployProcess

This time we don't have any error when loading another content type for the requestBody parameter, we even provide an example for each content types (all using the exact same CWL file).

Nevertheless, the minimal schema for CWL would be helpful to have something relevant when there is no example defined within the API.

**Comment by gfenoy** [comment]
I have finally used https://raw.githubusercontent.com/common-workflow-language/cwl-v1.2/1.2.1_proposed/CommonWorkflowLanguage.yml as schema for application/cwl+json there: [16ba65b](https://github.com/opengeospatial/ogcapi-processes/pull/327/commits/16ba65b4b0998318cf2ea1851c831daf6c573a88).

I hope it is correct, feedbacks are welcome.

**Comment by gfenoy** [comment]
With [b47410e](https://github.com/opengeospatial/ogcapi-processes/pull/327/commits/b47410e1375990f7ca76cac78f8aba2c8dd66f72) we get back to the trick using the schema object with an example field.

You can find here: https://app.swaggerhub.com/apis/ZOO-Project/the-zoo_project_wps_ogc_api_processing_development_server/GIT_2023-oas3#/DRU/replace the latest bundle generated with swagger-cli bundle.

**Comment by fmigneault** [comment]
@gfenoy 
I looked at the reference. This is actually a Schema Salad YAML definition, not an OpenAPI / JSON Schema. 
I don't think OpenAPI is able to parse it.

**Comment by gfenoy** [comment]
@fmigneault  Thanks a ton for the help!

The work on providing the schema for CWL you handle should solve this issue, once we will update to make reference to it (cf. https://github.com/opengeospatial/ogcapi-processes/pull/329) I think we should be fine.

**Comment by pvretano** [comment]
Closed by #327
