### ISSUE TITLE
outputTransmission and jobControlOptions not clearly explained

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-processes#326]
I'm pretty much reading OGC API Processes - Part 1 for the first time in detail.
I found `outputTransmission` and `jobControlOptions` in the specification accompanied by a schema. 
Unfortuantely, it is not clearly explained what these fields what they are for (or I missed it).
Also it seems the enum values defined in the JSON Schema are not explained.

**Comment by jerstlouis** [comment]
@m-mohr @pvretano Although `outputTransmission` might be gone in the next version, I believe `jobControlOptions` remains as the way to tell whether a particular process can be executed synchronously and/or asynchronously.

The `dismiss` here might be saying that a specific

It would be good if we could link to an auto-generated draft of Processes - Part 1: Core 2.0.

**Comment by fmigneault** [comment]
Indeed. They are not gone completely (nor should be), but rather replaced by the `Prefer` header approach.

**Comment by pvretano** [comment]
21-AUG-2023: `jobControlOptions` is still used in the process description to indicate whether a process can be executed synchronously, asynchronously or both.  Executing a processes sync or async is indicated using the `Prefer` header.  The `outputTransmission` parameter is still in the processes description but should not be as it is no longer used.  @pvretano will verify and remove it if necessary and then close this issue via a PR.
