### ISSUE TITLE
Reconsider status codes for DRU immutable and duplicate process responses

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#328]
[`/req/deploy-replace-undeploy/deploy/response-duplicate`](https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/deploy_replace_undeploy/standard/requirements/deploy-replace-undeploy/deploy/REQ_response-duplicate.adoc) and [`/req/deploy-replace-undeploy/deploy/response-immutable`](https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/deploy_replace_undeploy/standard/requirements/deploy-replace-undeploy/deploy/REQ_response-immutable.adoc) both use the same "error" code `303 See Other`. 

This makes it impossible for a Web Client interacting with the API to properly handle the problem, because it could be any of the two errors. Futhermore, many clients automatically handle `3xx` codes by silently/automatically following the returned redirect `Location`, causing the final response toward an existing process to be `200 OK`. This leads to potential confusion by the Web Client user (ie: the user deploys/deletes a process, gets an `200 OK`, but the obtained process description is wrong/still defined). Also, the `Location` of the "other" process could point toward a resource that is unaccessible, due to security restrictions or limitations for the identified user performing the original request. This instead can cause Authentication 401 or 403 responses after following the `Location`, which is even less descriptive about the cause of the problem.

In the case of a duplicate process, `409 Conflict` would be more relevant:
> 409 Conflict
> The request could not be completed due to a conflict with the current state of the resource. 
> [...] Whenever a resource conflict would be caused by fulfilling the request. Duplicate entries and deleting root objects when cascade-delete is not supported are a couple of examples.

In the case of an immutable process, the `403 Forbidden` operation would make more sense:
> 403 Forbidden
> The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated. If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity.

On top of being more relevant codes to illustrate the error that occured, 4xx are actually classified as "Client Error". 
Codes in the 3xx group are for redirections (aka the equivalent of 2xx but with an extra `Location`), which is misleading to indicate errors.

**Comment by fmigneault** [comment]
@pvretano @jerstlouis @gfenoy Thoughts about this?

**Comment by gfenoy** [comment]
@fmigneault thanks a lot for pointing this out.

I am in favour of this modifications and would be please to work on integrating them in this [PR](https://github.com/opengeospatial/ogcapi-processes/pull/327).

**Comment by gfenoy** [comment]
@fmigneault I have integrated the modifications here: https://github.com/GeoLabs/ogcapi-processes/commit/dbac653f86a4625ef59616b43067759f368c8637#diff-6126b7f18b1eafbd6697a4be54ec5ec85dbbde6c71422940ff7d5bba582e95d6.

Please confirm that it fixes the issue.

**Comment by gfenoy** [comment]
@fmigneault thanks your feedback.

This time it should be fine.

**Comment by pvretano** [comment]
21-AUG-2023:  Closed by #327.
