### ISSUE TITLE
Organization of the September 2023 OGC API - Processes Virtual Code Sprint

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#330]
This will be a SWG Code Sprint, organised by SWG Members, and open to the general public. 

- [x] SWG/DWG Chair identifies a date for the code sprint. **The code sprint will be held 18 to 20 September.**
- [x] SWG/DWG Chair identifies a mode for the code sprint, if it is to be a hybrid event. **This will be a virtual-only code sprint.**
- [x] At least 3 months before the envisioned event date, the SWG/DWG Chair submits an Event Request to the OGC Event Manager.
- [x] OGC Staff discuss the proposed sprint schedule and together deconflict the event from other OGC event
- [x] OGC Staff confirm the dates have been reserved for the code sprint
- [x] SWG/DWG Chair identifies SWG Member to serve as SWG Event Organizer. @bpross-52n confirmed as the SWG Event Organizer during the 2023-06-26 SWG telecon.
- [x] SWG Event Organizer prepares initial draft announcement for Press Release.
- [x] OGC DevRel adds the Sprint to the OGC Developer Website.
- [x] OGC DPM adds the Sprint to the OGC API Website (if sprint involves OGC APIs).
- [x] SWG Event Organizer populates the GitHub wiki page on the developer-events repository.
- [x] SWG Chair reviews and approves the announcement for Press Release .
- [x] OGC DPM or DevRel reviews and approves the announcement for Press Release.
- [x] SWG Event Organizer prepares registration page on the ogcapi-processes GitHub repo (for example, [this one](https://github.com/opengeospatial/ogcapi-processes/blob/master/workshops/2021_06_Workshop_Registration.adoc).  )
- [x] SWG Event Organizer updates the Agenda with names of speakers.
- [x] SWG Event Organizer invites SWG members to be Stream Leaders and/or Mentors.
- [x] SWG Event Organizer confirms communication platforms for the event. (**Preference stated on 2023-06-26 as Gotomeeting and [Gitter](https://app.gitter.im/#/room/#ogc-developer_Sprints:gitter.im)**).
- [x] SWG Event Organizer sends out 1st notification to participants, with logistics details (one month before sprint)
- [x] SWG Event Organizer sends out 2nd notification to participants, with logistics details (two weeks before sprint)
- [x] SWG Event Organizer sends proposals for social media posts to the OGC Communications Manager (two months before)
- [x] All SWG members spread the word about the event among their contacts
- [x] SWG Event Organizer sends out Final notification to participants, with logistics details (1 day before sprint)
- [x] Hold the Sprint event

**Comment by ghobona** [comment]
### Notes from 2023-06-26 SWG telecon

- [ ] @ghobona to provide @bpross-52n with a template for Press Releases announcing code sprints.
- [ ] @doublebyte1 to confirm location of the sprint website.
- [ ] @bpross-52n to identify some suitable free-to-use graphics from [Unsplash](https://unsplash.com/)  . To send the suggestions to the OGC Marketing Team. Deadline July 3rd, 2023.

Agreement: The sprint will use the ogcapi-processes repository (https://github.com/opengeospatial/ogcapi-processes),  so that the SWG has greater control over merging of pull requests

#### Communications Platform

The following plan was identified as preferable to because it gives the SWG greater control over the running of the code sprint.

Plan A
* Gotomeeting would be used for the plenary sessions.
* Gitter would be used for the chat.

Plan B
* Discord

Notifications will be sent out through Gitter and/or through a GitHub Issue. The participants will be asked to Watch the specific GitHub Issue.

**Comment by ghobona** [comment]
@pvretano @jerstlouis Please update the OpenAPI definition documents, especially the bundle version.

**Comment by jerstlouis** [comment]
#353

**Comment by ghobona** [comment]
LinkedIn post https://www.linkedin.com/feed/update/urn:li:share:7091764746189721600

**Comment by ghobona** [comment]
During the code sprint, the OGC API - Processes - Part 1: Core v2.0.0 candidate standard will be automatically built every two hours between 13:30 and 21:30 UTC.

The document can be found at https://opengeospatial.github.io/ogcna-auto-review/18-062r3.html

**Comment by ghobona** [comment]
All, thanks for participating in the code sprint, and for the great team work.

Special thanks to @bpross-52n for serving as the SWG Event Organiser.
