### ISSUE TITLE
Do we really need additional parameters?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#351]
In [descriptionType.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/processes-core/descriptionType.yaml) we have a complete structure for additional parameters.  Since by default `additionalProperties` is `true` anyone who wants to add "additional parameters" can simply add additional properties to the description.  Why all the extra baggage? 
Is the `additionalParameters` stuff a hold over from the XML days?  
Should we simplify things and get rid of all the `additionalParameters` stuff?

**Comment by jerstlouis** [comment]
@pvretano I guess this was to give some structure, in particular this `parameters` for those additional properties that are not elsewhere, but what is this intended for really?

_descriptionType.yaml_ is used in a few places (processSummary, inputDescription, outputDescription) does it make sense in any of these contexts? I don't think we use that anywhere in our implementation, only `title` and `description`.

I think we should get rid of all the `additionalParameters` stuff.

@gfenoy ?

**Comment by gfenoy** [comment]
> In [descriptionType.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/processes-core/descriptionType.yaml) we have a complete structure for additional parameters. Since by default `additionalProperties` is `true` anyone who wants to add "additional parameters" can simply add additional properties to the description. Why all the extra baggage?
> Is the `additionalParameters` stuff a hold over from the XML days?

You are right, the `additionalParameters` comes from the [OWS common 2.0 schema](https://schemas.opengis.net/ows/2.0/owsAdditionalParameters.xsd). When we were initially modifying the ZOO-Project to support OGC API - Processes, we realised that there were no way to include the additionalParameters that was present in the ProcessDescription available in WPS 2.0 and some of our client applications were requiring them. For backward compatibility with previous WPS implementations, I don't think it would hurt to keep it in the schema. Also, it may ease existing WPS 2.0 implementations to be ported to the current standard.

On the other hand, we are currently using the `additionalParameters` in our DRU+HPC implementation which is able to deploy processes and execute them on a remote HPC. You can access an exemple request to deploy such a process [here](https://github.com/ZOO-Project/ZOO-Project/blob/main/zoo-project/zoo-services/utils/hpc/examples/deployment-job.json) and the latest official binary docker image available [here](https://hub.docker.com/r/zooproject/zoo-project/tags?page=1&name=hpgc).

> Should we simplify things and get rid of all the `additionalParameters` stuff?

Is it causing any issue to keep it?

**Comment by pvretano** [comment]
@gfenoy no, its not causing a direct issue but I don't think we should keep random fragments of code around just for the sake of keeping them around.  This apparently is an artifact from the days of XML so I agree with @jerstlouis and think we can get rid of all the `additionalParameters` stuff.  This was added to OWS common because XML could only be extended schematically.  JSON is a little more flexible.

I'll create a PR where I get rid of this kruft that we can use as the basis of discussion.
