### ISSUE TITLE
Need to clarify the interaction between minOccurs, maxOccurs and schema in the input description.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#363]
There needs to be some clarifying text and perhaps examples added to the specification to explain the interaction between `minOccurs`, `maxOccurs` and `schema`.  

Specifically, 

1) The schema is used to express the definition of a **single** instance of an input.
2)  The `minOccurs` and `maxOccurs` members indicate the cardinality of that input. 
3) If the cardinality is 1 then an input value in an execute request can be assigned directly to the input
````
"x": 10
````
4) If the cardinality of an input is 1..N and only 1 input value is specified, that input value can be directly assigned to the input in an execute request.
````
"x": 10
````
5) If the cardinality of an input is 1..N and M input values are specified, those inputs values are assgined using an array in an execute request.
````
"x": [10, 7, 15, 34, 5]
````
6) If the cardinality of the input is N..M (e.g. 2..5) then input values are assigned using an array in an execute request:
````
"x": [1,2]
````
I've only used simple integer values as examples here but any value type (string, object, array, binary, etc.) would be handled the same way.  Also, I have only shown values being assinged by value but values assigned by reference would work the same ...

**Comment by gardengeek99** [comment]
I also want to understand better the relationship between minOccur and the "required" property in JSON Schema. Should we treat them independently or consult both to determine optional vs. required?
Doesn't minOccur of 0 mean the input is not required?

**Comment by jerstlouis** [comment]
@gardengeek99 The minOccurs of 0 means that an input as a whole is not required.

The required in the JSONSchema can be used to specify that a property "inside" an individual input (which itself is a JSON object) is required or not.
