### ISSUE TITLE
I/O `schema` definition uses conflicting `reference`

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#370]
Using either the original or the "patched" version for swagger-ui, the `schema` definition uses conflicting references.

https://github.com/opengeospatial/ogcapi-processes/blob/e81da042598a7e5bc0a81aff46cfcad1965d3d02/openapi/schemas/processes-core/schema.yaml#L68-L103

https://github.com/opengeospatial/ogcapi-processes/blob/e81da042598a7e5bc0a81aff46cfcad1965d3d02/openapi/schemas/processes-core/schema-original.yaml#L68-L105

Since `schema.yaml` itself does the `oneOf` of `reference.yaml` and the explicit `object` to represent a JSON-schema, each property nested under that object that should also support `$ref` do no need to do the `oneOf` as well. Simply using `$ref: schema.yaml` should be sufficient. 

https://github.com/opengeospatial/ogcapi-processes/blob/e81da042598a7e5bc0a81aff46cfcad1965d3d02/openapi/schemas/processes-core/schema-original.yaml#L1-L3

Currently, the 2 nested `oneOf` conditions will never succeed if `$ref` are used, since they would validate successfully against both branches indefinitely. This is probably the cause of the comments about swagger-ui, or at the very least, doesn't help it find a "final" recursion step.

**Comment by jerstlouis** [comment]
@fmigneault I always had trouble using recursive references in SwaggerUI.
But I think a failure with SwaggerUI does not necessarily mean that it is invalid JSON Schema or OpenAPI.

**Comment by fmigneault** [comment]
@jerstlouis I'm not actively using SwaggerUI to confirm, but it seems to work using python jsonschema validator and the embedded validator in my IDE. If you could validate if it works in SwaggerUI, that would be great! If not, I think this should still be fixed, and open an issue to SwaggerUI maintainers as needed. The viewer should not limit the spec.
