### ISSUE TITLE
Requirement or recommendation to link to `/results` in `/jobs/{jobId}`?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#377]
Right now it does not seem that there is any requirement or recommendation explicitly asking to link to `/results` in a successful job status, including in the latest draft 1.1/2.0. The `[ogc-rel:results]` is mentioned in 5.2 Link relations and is used in Example 2 "A job list encoded as JSON", but not mentioned anywhere else.

Is this an omission? Thanks.

@pvretano @bpross-52n

**Comment by pvretano** [comment]
@jerstlouis I'll check and add if missing.

**Comment by pvretano** [comment]
13-NOV-2023: Add a recommendation (not a requirement) to maintain backward compatability.  Needs to added to job list and job status.
