### ISSUE TITLE
Requirement for rel: self in process description / process list elements?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#381]
Should it be required that a "self" link is included in the process list and/or process description (to `/processes/{processId}`?)

Currently, there doesn't seem to be any requirement about this in 1.0 or the latest 1.1/2.0 draft.

The examples do include one.

Our client relies on this and this is breaking GDC TIEs.

cc. @pvretano

**Comment by bpross-52n** [comment]
SWG telecon from 8th January 2024: @pvretano will check other specifications and align API - Processes with them.
