### ISSUE TITLE
OGC API - Processes SWG participation in Code Sprint

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ogcapi-processes#393]
I plan to attend the [OGC-ASF-OSGeo code sprint](https://developer.ogc.org/sprints/23/) on-site and work on the [ZOO-Project](http://zoo-project.org), which is an OSGeo project.

I am willing to work on the [OGC API - Processes - Part 3: Workflow & Chaining draft specification](https://docs.ogc.org/DRAFTS/21-009.html), specifically reviewing the `nested-processes` and `remote-core-processes` Requirements Classes.

My main tasks will be testing the workflow & chaining support available in the ZOO-Project, writing documentation, and setting up a demonstration server instance, including ready-to-use workflow examples.

I also plan to review how to integrate Apache Airflow to deploy processes using the Part 2 draft specification.

**Comment by gfenoy** [comment]
Anyone willing to work on the OGC API - Processes during the coming OGC-ASF-OSGeo code sprint is invited to update this issue with the description of the work to be handled.

**Comment by fmigneault** [comment]
I'm also interested to work on Part 3 Workflows (same requirements). If some references to remote servers/processes can be shared to define a workflow that is expected to work, that would be great.

**Comment by jerstlouis** [comment]
Hi @fmigneault , @gfenoy . I also plan to be there in-person and though I will probably be working on a few different things, I would be very happy to do some Processes-3 breakout and work on getting more TIEs going.

To clarify those 2 req. classes specifically:

- _nested-processes_: This is being able to use a "process" object as an input to another process
- _remote-core-processes_: This is the ability of a server to execute processes using OGC API - Processes - Part 1: Core from a remote OGC API - Processes implementation. The executing server may require such remote servers to be explicilty authorized / federated previously.

**Comment by bpross-52n** [comment]
SWG meeting from 2024-08-05: The code sprint is over. We will close this issue.
