### ISSUE TITLE
Search Jobs function

### ISSUE THREAD

**Issue by samadammeek** [opengeospatial/ogcapi-processes#408]
Looking at using this standard for exposing quantum processes. Amazon bracket has a search function for jobs https://docs.aws.amazon.com/braket/latest/APIReference/API_SearchJobs.html
will this be supported?

**Comment by mike-gangl** [comment]
The [proceses-spec](https://docs.ogc.org/is/18-062r2/18-062r2.html#toc49) has a `/jobs` endpoint that should have a the ability to support some filtering parameters. Section 11.2 mentions:

```
type
process_id
status
datetime
minDuration
maxDuration
limit
```

though these are not available in the supplied [openapi.spec](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi.yaml).

**Comment by jerstlouis** [comment]
We're also considering the "Local Resources Collection" catalog as a way to allow Records API capabilities on `/processes` (see https://docs.ogc.org/DRAFTS/20-004.html#clause-local-resources-catalog , related to https://github.com/opengeospatial/ogcapi-records/issues/300).

**Comment by bpross-52n** [comment]
@samadammeek what do you think about the filtering parameters? It seems most of the parameters that AWS offers are there. If more functionality is neede, could this be something for the quantum computing profile/extension?
