### ISSUE TITLE
Adding ows:additionalProperties and ows:context to metadata

### ISSUE THREAD

**Issue by christophenoel** [opengeospatial/ogcapi-processes#42]
The REST spec only includes metadata which is an abstract type which may be specialized. 

OWS defines one specialization : ows:additionalParameters which allow to provide key value pairs metadata information. It is widely used including in OGC TEstbed 14 NextGen for including specific information: https://raw.githubusercontent.com/spacebel/testbed14/master/json-examples/Geomatys/MultiSensorNDVIStacker/deploy_multiSensor_byEMS.json
The following commit adds the definition of additionalParameters: https://github.com/opengeospatial/wps-rest-binding/commit/b2cca7914ddde393c34969fa677f113e25a342b9

OGC Testbed 13 and 14 also recommend defining ows:metadata type for embedding ows:context . Such element is recommended for providing everything need for retrieving a resource on another OGC service. When an input may be retrieve from a catalogue, tile service, coverage service, etc. this helps the WPS client to interface with the related OGC services.
I have added the definition in this commit: https://github.com/opengeospatial/wps-rest-binding/commit/d904df3e8af036c317077fdbfadeb7d15e90f687

**Comment by spacebel** [comment]
I disagree with my old change request.  :)
I'm against all the legacy generic placeholder for possible extensions: when required, an extension should be defined properly.

**Comment by pvretano** [comment]
@spacebel are there specific keys in the current schemas that your propose we remove?  I checked the schemas and I don't see any owsContext key ... although there are additionalParameter and metadata schemas.
