### ISSUE TITLE
JSON bundle broken

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-processes#438]
The bundle JSON at https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/ogcapi-processes.bundled.json seems to be malformed:

```bash
$ curl -s -O https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/openapi/ogcapi-processes.bundled.json
$ cat ogcapi-processes.bundled.json |python3 -m json.tool
Expecting ',' delimiter: line 3881 column 11 (char 185281)
```

Fixing the issue at line 3880 (adding a trailing comma) fixes the bundle, however I'm not sure if this bundle is auto-generated elsewhere.

cc @kalxas

**Comment by bpross-52n** [comment]
Closed by https://github.com/opengeospatial/ogcapi-processes/pull/439
