### ISSUE TITLE
Replace label with identifier key in all specification elements of Part 3

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#441]
Please replace `label` with `identifier` key in all specification elements of OGC API - Processes - Part 3: Workflows and Chaining.

![Screenshot 2024-09-30 at 14 48 27](https://github.com/user-attachments/assets/55d1c712-1ff8-4eca-8fd6-1dc8cfec6124)

See an example from OGC API - Maps at https://raw.githubusercontent.com/opengeospatial/ogcapi-maps/refs/heads/master/core/standard/requirements/requirements_class_core.adoc

**Comment by jerstlouis** [comment]
@ghobona fixed by #442
