### ISSUE TITLE
Execution of process via GET with query paramters

### ISSUE THREAD

**Issue by JakobMiksch** [opengeospatial/ogcapi-processes#463]
As far as I understood a process must be executed via a POST request as in this example ([source](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-processes.html)):

```shell
# execute a job for the ``shapely-functions`` process that computes the bounds of a WKT
curl -X POST http://localhost:5000/processes/shapely-functions/execution \
    -H "Content-Type: application/json" \
    -d "{\"inputs\":{\"operation\": \"measurement:bounds\",\"geoms\": [\"POINT(83.27651071580385 22.593553859283745)\"]}}"
```

Does the standard allow to additionally execute a process via a GET request with query params?

It could look like this then:

```text
http://localhost:5000/processes/shapely-functions/execution?
  operation=measurement:bounds&
  geoms=POINT(83.27651071580385 22.593553859283745)
```

I suppose having the option to execute the process via GET would simplify the usage a lot.
(PS: if this is not the right place to ask questions, I would kindly ask you to point me to the correct page/forum or mailing list)

**Comment by gfenoy** [comment]
I think it corresponds to the requirement class "KVP-encoded execute" from the [current editor's draft](https://docs.ogc.org/DRAFTS/18-062.html#_requirements_class_kvp_encoded_execute) available from the [README.md](https://github.com/opengeospatial/ogcapi-processes?tab=readme-ov-file#ogc-api---processes).

**Comment by JakobMiksch** [comment]
Great that's what I was looking for

**Comment by gfenoy** [comment]
I close this issue.

In case anything is missing in the response, please feel free to re-open or open another issue.
