### ISSUE TITLE
Part 4: Job Provenance endpoint mismatches GDC API Profile

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#464]
Part 4 currently proposes using `GET /jobs/{jobId}/run` for provenance (https://github.com/opengeospatial/ogcapi-processes/tree/master/extensions/job_management/standard/requirements/provenance/run).

In TB-20 GDC, the `GET /jobs/{jobId}/prov` endpoint is considered instead.

Given that the contents returned by `GET /jobs/{jobId}/run` are expected to be PROV specification (https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/job_management/standard/requirements/provenance/run/REQ_response.adoc), it makes sense to use `GET /jobs/{jobId}/prov`, and leave `GET /jobs/{jobId}/run` for other metadata (if any). 

Should the endpoint be changed, or an alias be defined?

**Comment by gfenoy** [comment]
If we find anything that should be considered, we can re-open this issue or open another issue.
