### ISSUE TITLE
Omitting maxOccurs vs. maxOccurs=unbounded

### ISSUE THREAD

**Issue by autermann** [opengeospatial/ogcapi-processes#49]
I don't see any semantic difference between simply omitting `maxOccurs` or specifying `maxOccurs: "unbounded"` for input descriptions. In favor of having only one type for the property, I'd propose to drop the latter...

**Comment by bpross-52n** [comment]
This change request was rejected in the SWG telecon from November 16th. 
Reason: Omitting min- or maxOccurs should indicate a default value of 1. Setting maxOccurs to "unbounded" should be stated expicitly by using the respective string value as it is currently specified.
