### ISSUE TITLE
Async conventions outside of Processes API

### ISSUE THREAD

**Issue by bilts** [opengeospatial/ogcapi-processes#59]
In implementing the Coverages API, it's clear that we need some sort of accommodation of asynchronous requests.  There exist coverage requests that we want to fulfill but cannot guarantee completion within any reasonable timeout.  Has there been thought toward making the async portions of the Processes API available to other APIs?  What would be the mechanism for doing this?

The previous WCPS standard seemed to bridge this gap, but I don't see anything between the new Coverages and Processes services.

**Comment by bpross-52n** [comment]
There is currently no separate conformance class for async execution in the OGC API - Processes. It is the default execution mode. Howevern this is subject to change, as we plan to also introduce a push-based async execution mechanism (in addition to the existing pull-based one). 

In general the question is whether it is feasible for the Coverages API to use a conformance class from the API - Processes or whether the async execution conformance classes should move to the API - Common and Coverages as well as Processes use those..

**Comment by bpross-52n** [comment]
See also here: https://docs.opengeospatial.org/per/18-045.html#async_extension

**Comment by jerstlouis** [comment]
I proposed that the async execution / `Prefer:` header / job management / status polling functionality of processes also be defined as a Common building blocks to use with any OGC APIs, e.g. for large coverage requests
See https://github.com/opengeospatial/ogcapi-common/issues/231#issuecomment-854942899 and https://github.com/opengeospatial/ogcapi-coverages/issues/66#issuecomment-844257494

**Comment by bpross-52n** [comment]
Closed as the use of the Prefer header is implemented in the specification.
