### ISSUE TITLE
process endpoint definitions

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-processes#6]
In example https://app.swaggerhub.com/apis/geoprocessing/WPS/0.01 process endpoints are defined in the OpenAPI document as:

`/processes/{id}`

If one wishes to explicitly articulate processes in the OpenAPI document as:

`/processes/foo`
`/processes/bar`

Is this considered equivalent to `/processes/{id}` ?

**Comment by bpross-52n** [comment]
Yes that is considered equivalent.

**Comment by tomkralidis** [comment]
Do this need to be articulated this in the specification (WPS or [OpenAPI common](https://github.com/opengeospatial/oapi_common))? cc @pvretano @cmheazel @cportele

**Comment by bpross-52n** [comment]
It is a common OpenAPI pattern to use either explicit or parameterized paths. There is no need to discuss this in the specification.
