### ISSUE TITLE
Statuses for partially successful requests

### ISSUE THREAD

**Issue by chris-durbin** [opengeospatial/ogcapi-processes#60]
There are currently four statuses - 'accepted', 'running', 'successful', and 'failed' for a processing request. We are looking for guidance on what status to use for requests that successfully processed some, but not all inputs. Would it make sense to allow an additional status along the lines of 'partially_failed'? Note that this also brings up a question of how to indicate which inputs were processed successfully and which failed though that might be worth a separate ticket to discuss.

Similarly, issue #52 mentions adding support for canceling a processing request. We too have this use case and were wondering if additional statuses should be added such as 'canceling' and 'canceled'. Potentially even something like 'partially_canceled' to indicate that part of the request was processed successfully, and other inputs were not processed as a result of being canceled. There's a balance to having too many allowed values for status, but I'm not sure if the current four statuses are enough.

**Comment by bpross-52n** [comment]
We discussed this briefly in one of our SWG telecons. I would like to invite you to discuss this issue more deeply in a telecon in 2021. Please let me know if that would be an option for you. Thanks!

**Comment by bpross-52n** [comment]
Closed due to inactivity. Feel free to reopen.
