### ISSUE TITLE
Use OGC DRAFTS document build?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-processes#74]
I see that API-Processes is available here: https://htmlpreview.github.io/?https://github.com/opengeospatial/wps-rest-binding/blob/master/docs/18-062.html

If you setup an asciidoctor.json like: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/asciidoctor.json 

And contact @gbuehler you can setup auto builds in the OGC DRAFTS http://docs.opengeospatial.org/DRAFTS/ space.

**Comment by bpross-52n** [comment]
Sounds reasonable. I will take care of it.

**Comment by bpross-52n** [comment]
Fixed, see: http://docs.ogc.org/DRAFTS/18-062.html
