### ISSUE TITLE
OGC-API transaction extension

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#76]
@pvretano Nice work for the addition of 'extensions'. 

I have noticed that in the context of both OGC-TB15 and OGC-TB16, many implementations take a reference file as `executionUnit[].href` (i.e.: HTTP URL to CWL file) or the literal content of that file as `executionUnit[].unit` object. The following definition should be updated to reflect this since there is no alternative method that explicitly details how to provide 'additionalParameters' that are specific to App Package from OGC-Process API schemas.

https://github.com/opengeospatial/wps-rest-binding/blob/528debd5023c7a37c80f4549518e8886db404a52/extensions/transactions/openapi/schemas/ogcapppkg.yaml#L11-L18

**Comment by pvretano** [comment]
I believe that this can be closed by PR #382.  @fmigneault can you confirm?

**Comment by fmigneault** [comment]
Yes. Closing.
